/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

/**
 *
 * @author Ale
 */
public class VentanaGanador extends javax.swing.JDialog {



    
    public VentanaGanador(java.awt.Frame parent, boolean modal, String ganador) {
        super(parent, modal);
        initComponents(ganador);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(String ganador) {

        jPanel1 = new javax.swing.JPanel();
        jlGanaste = new javax.swing.JLabel();
        jbJuegoNuevo = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jFelicitaciones = new javax.swing.JLabel();
        jGif = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlGanaste.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jlGanaste.setForeground(new java.awt.Color(255, 255, 255));
        jlGanaste.setText("Ganaste!!!");
        jPanel1.add(jlGanaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jbJuegoNuevo.setText("Jugar de nuevo");
        jbJuegoNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbJuegoNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jbJuegoNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 115, -1, -1));

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });
        jPanel1.add(jbSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(241, 144, -1, -1));

        jFelicitaciones.setFont(new java.awt.Font("Arial", 0, 26)); // NOI18N
        jFelicitaciones.setForeground(new java.awt.Color(255, 255, 255));
        jFelicitaciones.setText("Felicitaciones "+ganador);
        jPanel1.add(jFelicitaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        jGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ganadorresc.gif"))); // NOI18N
        jGif.setText("jLabel2");
        jGif.setMaximumSize(new java.awt.Dimension(340, 200));
        jGif.setMinimumSize(new java.awt.Dimension(340, 200));
        jGif.setPreferredSize(new java.awt.Dimension(340, 200));
        jPanel1.add(jGif, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 200));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jbJuegoNuevoActionPerformed(java.awt.event.ActionEvent evt) {                                             
        this.dispose();

       
    }                                            

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {                                        
        System.exit(0);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaGanador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaGanador dialog = new VentanaGanador(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jFelicitaciones;
    private javax.swing.JLabel jGif;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbJuegoNuevo;
    private javax.swing.JButton jbSalir;
    private javax.swing.JLabel jlGanaste;
    // End of variables declaration                   
}
